/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adderOrSubtractor_12 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg [7:0] final_sum,
    output reg z,
    output reg v,
    output reg n,
    output reg overflow
  );
  
  
  
  reg [8:0] sum;
  
  reg [8:0] s_sum;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        s_sum = a - b;
        sum = a + b;
      end
      2'h1: begin
        s_sum = a - b;
        sum = a - b;
      end
      2'h2: begin
        s_sum = a - b;
        sum = a * b;
      end
      2'h3: begin
        s_sum = a - b;
        sum = a - a / b * b;
      end
      default: begin
        s_sum = a - b;
        sum = a + b;
      end
    endcase
    final_sum = sum[0+7-:8];
    z = (~|sum[0+7-:8]);
    v = (a[7+0-:1] & b[7+0-:1] & (~sum[7+0-:1])) | ((~a[7+0-:1]) & (~b[7+0-:1]) & sum[7+0-:1]);
    overflow = (a[7+0-:1] & b[7+0-:1] & (~sum[7+0-:1])) | ((~a[7+0-:1]) & (~b[7+0-:1]) & sum[7+0-:1]);
    n = s_sum[7+0-:1];
  end
endmodule
